const words = {
  chay: {
    lang: 'Hebrew',
    pos: 'noun',
    definition: 'life/living thing',
    hint: 'Cows and humans have this in common',
    family: 'life',
  },
  chayyim: {
    lang: 'Hebrew',
    pos: 'noun',
    definition: 'life',
    hint: 'We saw this word first associated with a tree',
    family: 'life',
  },
  zoe: {
    lang: 'Greek',
    pos: 'noun',
    definition: 'life',
    hint: 'You experience this now and will hopefully experience it later too',
    family: 'life',
  },
  zao: {
    lang: 'Greek',
    pos: 'verb',
    definition: 'to live',
    hint: 'A verb you do every day',
    family: 'life',
  },
  zoopoieo: {
    lang: 'Greek',
    pos: 'verb',
    definition: 'to quicken/give life',
    hint: 'You might say that Lazarus was on the receiving end of this',
    family: 'life',
  },
  ahavah: {
    lang: 'Hebrew',
    pos: 'noun',
    definition: 'love',
    hint: '"L" is for the way you look at me...',
    family: 'love',
  },
  ahav: {
    lang: 'Hebrew',
    pos: 'verb',
    definition: 'to love',
    hint: 'This might be based on feeling or relationship',
    family: 'love',
  },
  agapao: {
    lang: 'Greek',
    pos: 'verb',
    definition: 'to love',
    hint: 'You might give this to your children',
    family: 'love',
  },
  agape: {
    lang: 'Greek',
    pos: 'noun',
    definition: 'love',
    hint: 'This is not conditioned on anything',
    family: 'love',
  },
  shem: {
    lang: 'Hebrew',
    pos: 'noun',
    definition: 'name',
    hint: 'There is one above all others',
    family: 'name',
  },
  onoma: {
    lang: 'Greek',
    pos: 'noun',
    definition: 'name',
    hint: 'There is one above all others',
    family: 'name',
  },
  dam: {
    lang: 'Hebrew',
    pos: 'noun',
    definition: 'blood',
    hint: 'This word is often associated with sacrifice.',
    family: 'blood',
  },
  haima: {
    lang: 'Greek',
    pos: 'noun',
    definition: 'blood',
    hint: 'This word appears only three times in the book of John',
    family: 'blood',
  },
  aman: {
    lang: 'Hebrew',
    pos: 'verb',
    definition: 'to believe/to trust/to be faithful',
    hint: 'We often close our prayers with a derivative of this word that means "let it be so"',
    family: 'believe',
  },
  pisteuo: {
    lang: 'Greek',
    pos: 'verb',
    definition: 'to believe/to trust/to be faithful/to give allegiance',
    hint: 'This is often given more than thought',
    family: 'believe',
  },
};

export default words;
