[build]
publish="public/"
command="yarn build"

[functions]
directory="functions/"

[[redirects]]
from="/auth"
to="/.netlify/functions/auth"
status=200

[[redirects]]
from="/api/profile"
to="/.netlify/functions/profile"
status=200

[[redirects]]
from="/*"
to="/index.html"
status=200